# Flask Options
DEBUG = True
SECRET_KEY = '5791628bb0b13ce0c676dfde280ba245'

# General JWT Options
JWT_TOKEN_LOCATION = ['cookies']
JWT_ALGORITHM = 'ES512'
JWT_PUBLIC_KEY = '''-----BEGIN PUBLIC KEY-----
MIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQBsg95IYXv1yEIBJhfSRf+OSC8kgPA
kYOFGe7vc9BA/MMMJV7IfmdssxWjj7oNW7nD5XfIBQXtUNnj/K8urQTIo5gAdxap
QqUfSCs7sBWiZXQGWwwBBhSw7bLbFvU5i87B1qISSjQEQj0/mf97qd/suIlESXlB
M1tWZ3lONvaDtSl8cCI=
-----END PUBLIC KEY-----'''
JWT_IDENTITY_CLAIM = 'sub'
JWT_ERROR_MESSAGE_KEY = 'message'

# Cookies JWT Options
JWT_ACCESS_COOKIE_NAME = 'access_token'
JWT_ACCESS_COOKIE_PATH = '/'
JWT_COOKIE_SECURE = False  # Send cookies over HTTPS only
JWT_COOKIE_DOMAIN = None
JWT_SESSION_COOKIE = False
JWT_COOKIE_SAMESITE = None
JWT_COOKIE_CSRF_PROTECT = False  # Enables CSRF protection
